# Generated by Django 4.1.7 on 2023-03-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cd_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='modification_date',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='registration_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modification_date',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='userprojectrelation',
            old_name='relations_created_date',
            new_name='created_at',
        ),
    ]
