# Generated by Django 4.1.7 on 2023-04-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cd_main', '0002_notificationstatus_remove_project_user_project_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cd_main.project'),
        ),
    ]
