# Generated by Django 4.1.7 on 2023-03-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_main', '0003_rename_update_at_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Enter project description', max_length=8192),
        )
    ]
