# Generated by Django 4.1.7 on 2023-03-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cd_main', '0004_alter_project_description_alter_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('code', models.CharField(max_length=127)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(help_text='Enter your full name', max_length=127),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cd_main.status'),
        ),
    ]
