# Generated by Django 4.1.7 on 2023-03-18 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cd_main', '0005_status_alter_user_fullname_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=127),
            preserve_default=False,
        ),
    ]
