# Generated by Django 4.1.7 on 2023-03-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cd_main', '0007_remove_user_password_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='soft_delete',
        ),
    ]
